#!/usr/bin/env bash
#
# create-run.sh
# -------------
# Purpose:
#   Create a new run workspace and seed it with the minimum files the rest of the
#   toolchain expects.
# Inputs:
#   Optional explicit run ID as the first argument.
# Outputs:
#   A run directory tree plus starter manifest, profile, and hypotheses files.
# Lifecycle role:
#   This establishes the system-of-record directory for a single campaign run.

# Fail fast on command errors, unset variables, and failed pipelines.
set -euo pipefail

# Resolve the repository root and the parent directory that stores all runs.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUN_ROOT="$REPO_ROOT/toolchain/runs"

# If the caller does not provide a run ID, generate one from the current UTC time.
RUN_ID="${1:-RUN-$(date -u +%Y-%m-%dT%H%M%SZ)}"
RUN_DIR="$RUN_ROOT/$RUN_ID"

# Create the standard directory layout used by manifests, tasks, evidence, and reports.
mkdir -p \
  "$RUN_DIR/tasks" \
  "$RUN_DIR/payloads" \
  "$RUN_DIR/evidence" \
  "$RUN_DIR/findings" \
  "$RUN_DIR/validation" \
  "$RUN_DIR/reports" \
  "$RUN_DIR/logs"

# Seed the run manifest by replacing the __RUN_ID__ token in the JSON template.
sed "s/__RUN_ID__/$RUN_ID/g" \
  "$REPO_ROOT/toolchain/templates/run-manifest.template.json" \
  > "$RUN_DIR/00-manifest.json"

# Create a placeholder system profile that later discovery work will replace.
cat > "$RUN_DIR/01-system-profile.md" <<'EOF'
# System profile

- status: pending discovery
- notes: generated by `create-run.sh`
EOF

# Create an empty hypotheses array so downstream tooling always has a predictable file.
cat > "$RUN_DIR/02-hypotheses.json" <<'EOF'
[]
EOF

# Print the run ID for wrapper scripts and humans.
printf '%s\n' "$RUN_ID"
