"""Output renderers for the simplified source-review flow."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable, List

from models import Finding, GeneratedTest, to_jsonable


SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2}


def write_json(path: Path, payload: object) -> None:
    """Write JSON with stable formatting."""

    path.write_text(json.dumps(to_jsonable(payload), indent=2) + "\n", encoding="utf-8")


def render_findings_markdown(findings: List[Finding]) -> str:
    """Render a beginner-readable findings summary grouped by severity."""

    lines: List[str] = ["# Findings", ""]
    if not findings:
        lines.extend(
            [
                "No findings were generated by the current heuristic pass.",
                "",
                "That does not prove the target repository is safe. It only means the current simplified checks did not match anything notable.",
            ]
        )
        return "\n".join(lines) + "\n"

    grouped = {}
    for finding in findings:
        grouped.setdefault(finding.severity, []).append(finding)

    for severity in ("high", "medium", "low"):
        severity_findings = grouped.get(severity, [])
        if not severity_findings:
            continue
        lines.extend([f"## {severity.title()}", ""])
        for finding in severity_findings:
            lines.extend(
                [
                    f"### {finding.finding_id}: {finding.title}",
                    f"- Category: `{finding.category}`",
                    f"- File: `{finding.file_path}`",
                    f"- Line: `{finding.line_number}`" if finding.line_number else "- Line: not inferred",
                    f"- Evidence: `{finding.evidence}`",
                    f"- Why it matters: {finding.reasoning}",
                    f"- Suggested test: {finding.suggested_test}",
                    "",
                ]
            )
    return "\n".join(lines)


def build_generated_test(finding: Finding) -> GeneratedTest:
    """Convert a finding into a language-agnostic Markdown test specification."""

    route_context = f" Review the route hinted by `{finding.route_hint}`." if finding.route_hint else ""
    curl_script_name = (
        f"{finding.finding_id}-confirm.sh"
        if finding.curl_confirmable and finding.route_hint
        else None
    )

    return GeneratedTest(
        finding_id=finding.finding_id or "UNASSIGNED",
        title=finding.title,
        target_file=finding.file_path,
        why_it_matters=finding.reasoning,
        preconditions=[
            "Access to a safe test or staging environment if runtime confirmation is required.",
            "Knowledge of the input path that reaches the code shown in the evidence.",
        ],
        suggested_setup=[
            "Review the source file and nearby call path to identify the relevant input fields or route.",
            "Prepare benign baseline input and one malicious or boundary-case input.",
        ],
        test_steps=[
            f"Inspect the source evidence near line {finding.line_number or 'unknown'} in `{finding.file_path}`.",
            f"Exercise the code path that matches this finding category.{route_context}",
            f"Use the following direction for the test: {finding.suggested_test}",
            "Capture the response, error behavior, and any resulting side effects.",
        ],
        expected_secure_behavior=[
            "The application should validate, reject, or safely neutralize the risky input.",
            "No privileged behavior, sensitive data exposure, or unsafe side effects should occur.",
        ],
        expected_vulnerable_behavior=[
            "The risky input is accepted or executed in a way that confirms the finding.",
            "The application leaks data, bypasses controls, or performs an unsafe action.",
        ],
        curl_script_name=curl_script_name,
    )


def render_test_markdown(test: GeneratedTest) -> str:
    """Render one generated test specification as Markdown."""

    lines = [
        f"# {test.finding_id}: {test.title}",
        "",
        f"- Target file: `{test.target_file}`",
        f"- Why it matters: {test.why_it_matters}",
        "",
        "## Preconditions",
        "",
    ]
    lines.extend(f"- {item}" for item in test.preconditions)
    lines.extend(["", "## Suggested setup", ""])
    lines.extend(f"- {item}" for item in test.suggested_setup)
    lines.extend(["", "## Test steps", ""])
    lines.extend(f"1. {step}" for step in test.test_steps)
    lines.extend(["", "## Expected secure behavior", ""])
    lines.extend(f"- {item}" for item in test.expected_secure_behavior)
    lines.extend(["", "## Expected vulnerable behavior", ""])
    lines.extend(f"- {item}" for item in test.expected_vulnerable_behavior)
    if test.curl_script_name:
        lines.extend(
            [
                "",
                "## Optional curl confirmation",
                "",
                f"- See `{test.curl_script_name}` in the same directory for a starter confirmation template.",
            ]
        )
    return "\n".join(lines) + "\n"


def render_curl_script(finding: Finding) -> str:
    """Render a starter curl confirmation template for HTTP-like findings."""

    route = finding.route_hint or "/replace-with-route"
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "#",
            f"# {finding.finding_id} confirmation template",
            "# This is a starter curl command derived from a source review finding.",
            "# You must adapt TARGET_BASE_URL, TOKEN, IDs, and payloads to your test environment.",
            "",
            'set -euo pipefail',
            "",
            ': "${TARGET_BASE_URL:?set TARGET_BASE_URL}"',
            ': "${TOKEN:=replace-me}"',
            ': "${RESOURCE_ID:=replace-me}"',
            "",
            "curl -i \\",
            f'  "$TARGET_BASE_URL{route}" \\',
            '  -H "Authorization: Bearer $TOKEN" \\',
            '  -H "Accept: application/json"',
            "",
        ]
    ) + "\n"


def sort_findings(findings: Iterable[Finding]) -> List[Finding]:
    """Return findings sorted by severity, file path, and line number."""

    return sorted(
        findings,
        key=lambda finding: (
            SEVERITY_ORDER.get(finding.severity, 99),
            finding.file_path,
            finding.line_number or 0,
            finding.category,
        ),
    )
